clc; clear; close all;
h= 0.01; t(1)=0; tfinal=52; t=t(1):h:tfinal; N=ceil((tfinal-t(1))/h); % Inputs
S(1) = 2.67e7;
V(1) = 9.61e6;
E(1) = 7;
I(1) = 1;
H(1) = 0;
R(1) = 0;
% Total Population
N1 = S(1) + V(1) + E(1) + I(1) + H(1) + R(1);
alpha=0.95; % this is fractional order
tau=1; % this is fractal dimension
sigma1 = 0.114; % Previously alpha
sigma2 = 0.858; % Previously beta
sigma3 = 0.0015; % Previously epsilon
sigma4 = 1.00; % Previously sigma
sigma5 = 0.34; % Previously gamma1
sigma6 = 0.68; % Previously gamma2
sigma7 = 1/7; % Previously omega
sigma8 = 1/10; % Previously gamma
sigma9 = 1/180; % Previously rho
sigma10 = 1/(70*365); % Previously mu
sigma11 = 1e4; % Previously lambda
% The Model (3.4) in the Research Paper
f1 = @(t,S,V,E,I,H,R) sigma11 + sigma9*(V+R)-sigma2*(E + I).*S / N1 - (sigma1 + sigma10)*S;
f2 = @(t,S,V,E,I,H,R) sigma1 * S - sigma4 * sigma2 * (E + I) .* V / N1 - (sigma9 + sigma10)*V;
f3 = @(t,S,V,E,I,H,R) sigma2 * (E + I).* (S + sigma4 * V) / N1 - (sigma7 + sigma5 + sigma10)*E;
f4 = @(t,S,V,E,I,H,R) sigma7*E - (sigma8 + sigma3 + sigma10)*I;
f5 = @(t,S,V,E,I,H,R) sigma3*I-(sigma6 + sigma10)*H;
f6 = @(t,S,V,E,I,H,R) sigma5 * E + sigma8 * I + sigma6 * H - (sigma9 + sigma10) * R;
% Algorithm of the Caputo Fractal-Fractional starts
for n=1:N
    j=2:n;
    S(n+1)=S(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f1(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f1(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    V(n+1)=V(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f2(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f2(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    E(n+1)=E(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f3(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f3(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    I(n+1)=I(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f4(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f4(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    H(n+1)=H(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f5(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f5(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    R(n+1)=R(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f6(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f6(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    t(n+1)=t(n)+h;
end
figure
plot(t, I, 'LineWidth', 1.5);

hold on

alpha=0.90; % this is fractional order
tau=1; % this is fractal dimension
% Algorithm of the Caputo Fractal-Fractional starts
for n=1:N
    j=2:n;
    S(n+1)=S(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f1(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f1(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    V(n+1)=V(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f2(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f2(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    E(n+1)=E(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f3(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f3(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    I(n+1)=I(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f4(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f4(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    H(n+1)=H(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f5(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f5(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    R(n+1)=R(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f6(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f6(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    t(n+1)=t(n)+h;
end
%figure;
plot(t, I, 'LineWidth', 1.5);


hold on

alpha=0.85; % this is fractional order
tau=1; % this is fractal dimension
% Algorithm of the Caputo Fractal-Fractional starts
for n=1:N
    j=2:n;
    S(n+1)=S(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f1(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f1(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    V(n+1)=V(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f2(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f2(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    E(n+1)=E(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f3(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f3(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    I(n+1)=I(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f4(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f4(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    H(n+1)=H(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f5(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f5(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    R(n+1)=R(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f6(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f6(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    t(n+1)=t(n)+h;
end
%figure;
plot(t, I, 'LineWidth', 1.5);


hold on

alpha=0.80; % this is fractional order
tau=1; % this is fractal dimension
% Algorithm of the Caputo Fractal-Fractional starts
for n=1:N
    j=2:n;
    S(n+1)=S(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f1(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f1(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    V(n+1)=V(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f2(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f2(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    E(n+1)=E(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f3(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f3(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    I(n+1)=I(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f4(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f4(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    H(n+1)=H(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f5(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f5(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    R(n+1)=R(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f6(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f6(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    t(n+1)=t(n)+h;
end
%figure;
plot(t, I, 'LineWidth', 1.5);


hold on

alpha=0.75; % this is fractional order
tau=1; % this is fractal dimension
% Algorithm of the Caputo Fractal-Fractional starts
for n=1:N
    j=2:n;
    S(n+1)=S(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f1(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f1(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    V(n+1)=V(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f2(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f2(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    E(n+1)=E(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f3(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f3(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    I(n+1)=I(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f4(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f4(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    H(n+1)=H(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f5(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f5(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    
    R(n+1)=R(1)+(tau*(h^alpha)./gamma(alpha+2)).*sum(((n+1-j).^alpha.*...
        (n-j+2+alpha)-(n-j).^alpha .* (n-j+2+2*alpha)).*...
        f6(t(j),S(j),V(j),E(j),I(j),H(j),R(j)).*t(j).^(tau-1)-((n+1-j).^(alpha+1)-(n-j).^alpha.*...
        (n-j+1+alpha)).*f6(t(j-1),S(j-1),V(j-1),E(j-1),I(j-1),H(j-1),R(j-1)).*t(j-1).^(tau-1));
    t(n+1)=t(n)+h;
end
%figure;
plot(t, I, 'LineWidth', 1.5);
xlabel('Time (weeks)');
ylabel('nfectious individuals');
legend('$\alpha$ = 0.95,$\tau$=1', '$\alpha$ = 0.90,$\tau$=1', '$\alpha$ = 0.85,$\tau$=1', '$\alpha$ = 0.80,$\tau$=1', '$\alpha$ = 0.75,$\tau$=1', 'Interpreter', 'latex');
xlim([0 52]);
grid on;